// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectPendragonBackend.Data;

#nullable disable

namespace ProjectPendragonBackend.Migrations
{
    [DbContext(typeof(ProjectPendragonDbContext))]
    [Migration("20221029135310_FurtherCharacterChanges")]
    partial class FurtherCharacterChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjectPendragonBackend.Models.Attributes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("App")
                        .HasColumnType("int");

                    b.Property<int>("Con")
                        .HasColumnType("int");

                    b.Property<int>("Dex")
                        .HasColumnType("int");

                    b.Property<int>("Siz")
                        .HasColumnType("int");

                    b.Property<int>("Str")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("ProjectPendragonBackend.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttributesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BirthNumber")
                        .HasColumnType("int");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("Culture")
                        .HasColumnType("int");

                    b.Property<string>("DistinctiveFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FathersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Glory")
                        .HasColumnType("int");

                    b.Property<string>("Home")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LiegeLord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TraitsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WealthId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearBorn")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttributesId");

                    b.HasIndex("SkillsId");

                    b.HasIndex("TraitsId");

                    b.HasIndex("WealthId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("ProjectPendragonBackend.Models.CombatSkills", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Battle")
                        .HasColumnType("int");

                    b.Property<int>("Dagger")
                        .HasColumnType("int");

                    b.Property<int>("GreatSpear")
                        .HasColumnType("int");

                    b.Property<int>("GreatWeapon")
                        .HasColumnType("int");

                    b.Property<int>("Horsemanship")
                        .HasColumnType("int");

                    b.Property<int>("Lance")
                        .HasColumnType("int");

                    b.Property<int>("Siege")
                        .HasColumnType("int");

                    b.Property<int>("Spear")
                        .HasColumnType("int");

                    b.Property<int>("SpearExpertise")
                        .HasColumnType("int");

                    b.Property<int>("Sword")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CombatSkills");
                });

            modelBuilder.Entity("ProjectPendragonBackend.Models.Passion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Passion");
                });

            modelBuilder.Entity("ProjectPendragonBackend.Models.Skills", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Awareness")
                        .HasColumnType("int");

                    b.Property<int>("Boating")
                        .HasColumnType("int");

                    b.Property<int>("Chirurgury")
                        .HasColumnType("int");

                    b.Property<Guid>("CombatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Compose")
                        .HasColumnType("int");

                    b.Property<int>("Courtesy")
                        .HasColumnType("int");

                    b.Property<int>("Dancing")
                        .HasColumnType("int");

                    b.Property<int>("Distaff")
                        .HasColumnType("int");

                    b.Property<int>("FaerieLore")
                        .HasColumnType("int");

                    b.Property<int>("Falconry")
                        .HasColumnType("int");

                    b.Property<int>("Fashion")
                        .HasColumnType("int");

                    b.Property<int>("FirstAid")
                        .HasColumnType("int");

                    b.Property<int>("Flirting")
                        .HasColumnType("int");

                    b.Property<int>("Folklore")
                        .HasColumnType("int");

                    b.Property<int>("Gaming")
                        .HasColumnType("int");

                    b.Property<int>("Heraldry")
                        .HasColumnType("int");

                    b.Property<int>("Hunting")
                        .HasColumnType("int");

                    b.Property<int>("Industry")
                        .HasColumnType("int");

                    b.Property<int>("Intrigue")
                        .HasColumnType("int");

                    b.Property<int>("Orate")
                        .HasColumnType("int");

                    b.Property<int>("PlayInstrument")
                        .HasColumnType("int");

                    b.Property<int>("ReadLatin")
                        .HasColumnType("int");

                    b.Property<int>("Recognize")
                        .HasColumnType("int");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.Property<int>("Romance")
                        .HasColumnType("int");

                    b.Property<int>("Singing")
                        .HasColumnType("int");

                    b.Property<int>("Stewardship")
                        .HasColumnType("int");

                    b.Property<int>("Swimming")
                        .HasColumnType("int");

                    b.Property<int>("Tourney")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CombatId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ProjectPendragonBackend.Models.Traits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Chaste")
                        .HasColumnType("int");

                    b.Property<int>("Energetic")
                        .HasColumnType("int");

                    b.Property<int>("Forgiving")
                        .HasColumnType("int");

                    b.Property<int>("Generous")
                        .HasColumnType("int");

                    b.Property<int>("Honest")
                        .HasColumnType("int");

                    b.Property<int>("Just")
                        .HasColumnType("int");

                    b.Property<int>("Merciful")
                        .HasColumnType("int");

                    b.Property<int>("Modest")
                        .HasColumnType("int");

                    b.Property<int>("Pious")
                        .HasColumnType("int");

                    b.Property<int>("Prudent")
                        .HasColumnType("int");

                    b.Property<int>("Temperate")
                        .HasColumnType("int");

                    b.Property<int>("Trusting")
                        .HasColumnType("int");

                    b.Property<int>("Valorous")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Traits");
                });

            modelBuilder.Entity("ProjectPendragonBackend.Models.Wealth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Denari")
                        .HasColumnType("int");

                    b.Property<int>("Libra")
                        .HasColumnType("int");

                    b.Property<int>("Shilling")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wealth");
                });

            modelBuilder.Entity("ProjectPendragonBackend.Models.Character", b =>
                {
                    b.HasOne("ProjectPendragonBackend.Models.Attributes", "Attributes")
                        .WithMany()
                        .HasForeignKey("AttributesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectPendragonBackend.Models.Skills", "Skills")
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectPendragonBackend.Models.Traits", "Traits")
                        .WithMany()
                        .HasForeignKey("TraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectPendragonBackend.Models.Wealth", "Wealth")
                        .WithMany()
                        .HasForeignKey("WealthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attributes");

                    b.Navigation("Skills");

                    b.Navigation("Traits");

                    b.Navigation("Wealth");
                });

            modelBuilder.Entity("ProjectPendragonBackend.Models.Passion", b =>
                {
                    b.HasOne("ProjectPendragonBackend.Models.Character", null)
                        .WithMany("Passions")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("ProjectPendragonBackend.Models.Skills", b =>
                {
                    b.HasOne("ProjectPendragonBackend.Models.CombatSkills", "Combat")
                        .WithMany()
                        .HasForeignKey("CombatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combat");
                });

            modelBuilder.Entity("ProjectPendragonBackend.Models.Character", b =>
                {
                    b.Navigation("Passions");
                });
#pragma warning restore 612, 618
        }
    }
}
